app/db/models.py
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import db
from dataclasses import dataclass
from typing import Optional


@dataclass
class Person(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(unique=True)
    email: Mapped[str]


@dataclass
class RawData(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[int]


@dataclass
class AvgData(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[Optional[int]] = mapped_column()


@dataclass
class MoistureReading(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[int]

models/base.py
from sqlalchemy.orm import declarative_base

Base = declarative_base()

models/models.py
from sqlalchemy.orm import Mapped, mapped_column
from dataclasses import dataclass
from typing import Optional
from sqlalchemy.orm import declarative_base

Base = declarative_base()


@dataclass
class Person(Base):
    __tablename__ = "person"
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(unique=True)
    email: Mapped[str]


@dataclass
class RawData(Base):
    __tablename__ = "raw_data"
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[Optional[int]] = mapped_column()


@dataclass
class AvgData(Base):
    __tablename__ = "avg_data"
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[Optional[int]] = mapped_column()


@dataclass
class MoistureReading(Base):
    __tablename__ = "moisture_reading"
    id: Mapped[int] = mapped_column(primary_key=True)
    timestamp: Mapped[int] = mapped_column(unique=True)
    value: Mapped[int]


@dataclass
class Weather(Base):
    __tablename__ = "weather_current"
    id: Mapped[int] = mapped_column(primary_key=True)
    key: Mapped[str] = mapped_column(unique=True)
    value: Mapped[Optional[str]] = mapped_column()

app.py
from app import create_app

app = create_app()
if __name__ == "__main__":
    app.run(debug=True)

app/__init__.py
from flask import Flask
from flask_login import LoginManager
import secrets
from app.user import User, users
from app.db.flask_db import db

login_manager = LoginManager()


@login_manager.user_loader
def user_loader(email):
    if email not in users:
        return

    user = User()
    user.id = email
    return user


@login_manager.request_loader
def request_loader(request):
    email = request.form.get("email")
    if email not in users:
        return

    user = User()
    user.id = email
    return user


def create_app(test_config=None):
    app = Flask(__name__)

    if test_config:
        app.config.update(test_config)
    else:
        app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///plant_info.db"

    # used user management. (sessions / messages etc.) now being created after the app is initalised.
    app.secret_key = secrets.token_hex(32)
    # TODO - figure out how to make this not refresh on every launch

    login_manager.init_app(app)
    login_manager.login_view = "auth.login"

    db.init_app(app)

    with app.app_context():
        db.create_all()

    # Register Blueprints
    from app.index import index_bp
    from app.charts import charts_bp
    from app.auth import auth_bp
    from app.admin import admin_bp
    from app.charts.api import api_bp
    from app.stats import stats_bp
    from app.dashboard import dashboard_bp
    from app.integrations.weather_api import weather_api_bp

    app.register_blueprint(index_bp)
    app.register_blueprint(charts_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(admin_bp)
    app.register_blueprint(api_bp)
    app.register_blueprint(stats_bp)
    app.register_blueprint(dashboard_bp)
    app.register_blueprint(weather_api_bp)

    return app

app/admin/__init__.py
from flask import Blueprint

admin_bp = Blueprint(
    "admin", __name__, url_prefix="/admin", template_folder="templates"
)
from . import admin  # noqa: E402, F401

app/charts/__init__.py
from flask import Blueprint

charts_bp = Blueprint("charts", __name__, template_folder="templates")
from . import charts, api  # noqa: E402, F401

app/dashboard/__init__.py
from flask import Blueprint

dashboard_bp = Blueprint("dashboard", __name__, template_folder="templates")
from . import dashboard  # noqa: E402, F401

app/index/__init__.py
from flask import Blueprint
index_bp = Blueprint("index", __name__, template_folder="templates")
from . import home  # noqa: E402, F401

app/stats/__init__.py
from flask import Blueprint

stats_bp = Blueprint("stats", __name__, template_folder="templates")
from . import stats  # noqa: E402, F401

blueprints/homepage.py
from flask import render_template
from flask import Blueprint
import sqlite3

homepage_bp = Blueprint("homepage", __name__, template_folder="templates")


@homepage_bp.route("/")
def index():

    # Reconnect to the DB
    connection = sqlite3.connect("plant_info.db")
    cursor = connection.cursor()

    # Fetch the last 30 entries of moisture data from the database and assign them to a variable
    cursor.execute("SELECT * FROM minute_reading ORDER BY date_time DESC LIMIT 1")
    rows = cursor.fetchone()
    raw_moisture_reading = rows[1]

    # Close the connection
    connection.close()

    current_moisture = translate_moisture(raw_moisture_reading)

    # print(current_moisture)

    # fake = [{"percent" : 23, "box_colour" : "green"}]

    # Give data to the html
    # return render_template('index.html', monthly_moisture=monthly_moisture)
    # return render_template('index.html', monthly_moisture=map(to_model,rows))
    # print(list(map(to_model,rows)))
    return render_template("index.html", current_moisture=current_moisture)


def translate_moisture(reading):

    # assume zero to be currently wet.
    # 500 seems to maximum reading in air, unsure about soil

    if reading == 0:
        translated_moisture_string = f"Can't get any wetter! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"
    elif reading <= 100:
        translated_moisture_string = (
            f"Soaked! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"
        )
    elif reading <= 200:
        translated_moisture_string = (
            f"Nice and moist! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"
        )
    elif reading <= 300:
        translated_moisture_string = f"Average, if no rain due consider watering! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"
    elif reading <= 400:
        translated_moisture_string = f"It's time to water! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"
    elif reading <= 400:
        translated_moisture_string = f"Sahara Desert, they're probably dead. Water immediately! <br/> Reading: {reading} <br/> Wetness Estimation: {(500-reading)/5}%"

    return translated_moisture_string

templates/base.html
<!DOCTYPE html>
<html lang="en" data-theme="forest">
  <head>
    <title>🍅 Tomato App</title> {# TODO CONVERT THIS TO DYNAMIC CONTENT#}
    <meta name="description" content="The best plant watering app ever!">
    <meta name="keywords" content="tomato, app, plant, watering">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5"
          rel="stylesheet"
          type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css"
          rel="stylesheet"
          type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {# <link rel="stylesheet"
       href="{{ url_for('static', filename='css/main.css') }}"> #}
    {% block head %}
    {% endblock head %}
  </head>
  <body class="flex flex-col min-h-screen">
    <div class="navbar bg-base-100 shadow-sm mb-10">
      <div class="flex-none">
        {# Dropdown Code #}
        <details class="dropdown">
          <summary class="btn btn-square btn-ghost">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 class="inline-block h-5 w-5 stroke-current">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </summary>
          <ul class="menu dropdown-content bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm">
            <li>
              <a href="{{ url_for('homepage.index') }}">Home</a>
            </li>
            <li>
              <a href="{{ url_for('charts.charts') }}">Charts</a>
            </li>
            <li>
              <a>Item 2</a>
            </li>
          </ul>
        </details>
      </div>
      <div class="flex-1">
        <a href="{{ url_for('homepage.index') }}" class="btn btn-ghost text-xl">🍅 Tomato App</a>
      </div>
      <div class="flex-none">
        <a href="{{ url_for('login.login') }}"
           class="text-neutral-content btn btn-ghost text-l bg-neutral">Login</a>
      </div>
    </div>
    {% block content %}
    {% endblock content %}
    <footer class="w-full bg-neutral text-neutral-content py-6 mt-16 fixed bottom-0">
      <div class="container mx-auto px-4 flex flex-col md:flex-row items-center justify-between">
        <p class="text-sm">© 2025 Tomato Tracker. All rights reserved.</p>
        <div class="flex space-x-4 mt-4 md:mt-0">
          <a href="#" class="text-sm hover:underline">About</a>
          <a href="#" class="text-sm hover:underline">GitHub</a>
          <a href="#" class="text-sm hover:underline">Contact</a>
        </div>
      </div>
    </footer>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/graph.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <canvas id="lineChart" width="1800" height="1200"></canvas>
    <script>
        var ctx = document.getElementById("lineChart").getContext("2d");
        var lineChart = new Chart(ctx, {
            type: "line",
            data: {
                labels: {{labels | safe }},
                datasets: [
                    {
                        label: "Data points",
                        data: {{ values | safe }},
                        fill: false, 
                        borderColor: "rgb(75, 192, 192)",
                        lineTension: 0.1
                    }
                ]
            },
            options: {
                responsive: false
            }

        })
    </script>

</body>
</html>